### ISSUE TITLE
pandasai error

### ISSUE THREAD

**Issue by rockettpc** [RafayKhattak/csvGPT#1]
I have tried running this locally and in the cloud using streamlit, both give errors regarding not being able to import PandasAI

**Comment by rockettpc** [comment]
You simply need to downgrade pandasai to an older version 

pip install pandasai==0.6.0

**Comment by RafayKhattak** [comment]
> You simply need to downgrade pandasai to an older version 
> 
> pip install pandasai==0.6.0

Thank you so much, I'll change it as soon as possible.

**Comment by rockettpc** [comment]
> > You simply need to downgrade pandasai to an older version
> > pip install pandasai==0.6.0
> 
> Thank you so much, I'll change it as soon as possible.

no problem, cool little app btw.
